message_server:
  listen_addr: 0.0.0.0
  listen_port: 51235

  in_encodings:
    - "1251"
    - "utf-8"
  
  out_encodings:
    - "1251"
    - "utf-8"


icecast_client:
  host: '127.0.0.1'
  port: 8004
  user: 'source'
  password: 'hackme'
  mount: '/stream.ogg'

  format_: 'mp3'
  protocol: 'http'
  name: 'my stream name'


logging:
  version: 1

  root:
    level: INFO
    handlers: [console]
  
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default

  formatters:
    default:
      format: '%(asctime)s %(levelname)-7s %(module)10s - %(message)s'